"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
except KeyError:
    raise ImproperlyConfigured(
        'A variável de ambiente DJANGO_SECRET_KEY não está definida. '
        'Gere uma chave com: python -c "from django.core.management.utils '
        'import get_random_secret_key; print(get_random_secret_key())"'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['.vercel.app', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',

    'ai',
    'app',
    'authentication',
    'brands',
    'categories',
    'inflows',
    'outflows',
    'products',
    'suppliers',

    'widget_tweaks',

    # Deve vir por último (ver docs do django-axes sobre ordem de apps/middleware).
    'axes',
]

LOGIN_URL = 'login'

LOGIN_REDIRECT_URL = '/home'
LOGOUT_REDIRECT_URL = '/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'app.middleware.DemoModeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Precisa ser o último middleware da lista (exigência do django-axes).
    'axes.middleware.AxesMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # Precisa vir antes do ModelBackend para o axes poder bloquear a
    # tentativa antes da senha ser validada.
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

CSRF_TRUSTED_ORIGINS = [
    'https://*.vercel.app',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['app/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.demo_mode',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'pt-BR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# DRF throttling (abaixo) guarda os contadores no cache do Django, que por
# padrão é LocMemCache — em memória do processo. Isso não sobrevive entre
# invocações na Vercel (serverless, sem estado local), exatamente o mesmo
# motivo pelo qual o django-axes é forçado pro AxesDatabaseHandler em vez do
# handler em cache (ver comentário mais abaixo). Sem isso, o throttle
# "funciona" localmente (processo único e duradouro) mas não limita nada em
# produção. Rodar `manage.py createcachetable` depois de configurar isso.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache',
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.DjangoModelPermissions',
    ),
    # Throttle global (contra abuso genérico da API) + um scope dedicado
    # pro /api/v1/ai/invoke/: cada chamada aciona a API paga da OpenAI, e
    # sem limite o próprio usuário demo pode gerar custo sem controle
    # (achado no QA da Fase 3).
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '2000/day',
        'ai_invoke': '10/hour',
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

OPENAI_MODEL = 'gpt-3.5-turbo'
# Usada apenas pelo comando de management `sge_agent_invoke` (ai/agent.py),
# não em toda requisição — por isso não é exigida no import de settings.py
# como a DJANGO_SECRET_KEY. Se ausente, o comando falha ao chamar a API.
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')

# Modo de demonstração pública (ver Etapa 3)
DEMO_MODE = os.environ.get('DEMO_MODE', 'False') == 'True'
RESET_TOKEN = os.environ.get('RESET_TOKEN', '')

# A Vercel injeta VERCEL=1 no ambiente de execução das funções serverless.
# Só força HTTPS/cookies seguros lá, para não quebrar testes locais via HTTP.
IS_VERCEL = os.environ.get('VERCEL') == '1'
SESSION_COOKIE_SECURE = IS_VERCEL
CSRF_COOKIE_SECURE = IS_VERCEL
SECURE_SSL_REDIRECT = IS_VERCEL

if IS_VERCEL:
    SECURE_HSTS_SECONDS = 31536000  # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'same-origin'

# django-axes: throttling de tentativas de login por IP.
#
# Por que django-axes e não uma solução caseira: é a lib mais madura do
# ecossistema Django para isso e se integra via AUTHENTICATION_BACKENDS,
# então cobre tanto o login de formulário (LoginView) quanto o endpoint
# JWT (TokenObtainPairView), que também passam por authenticate().
#
# Por que funciona na Vercel (serverless, sem estado local entre invocações):
# o handler é forçado para AxesDatabaseHandler, que grava as tentativas na
# tabela axes_accessattempt do Postgres (Neon), não em cache em memória do
# processo. Como a Vercel reinicia o processo a cada cold start, um handler
# baseado em cache local (LocMemCache) perderia o estado; o banco não.
AXES_HANDLER = 'axes.handlers.database.AxesDatabaseHandler'
AXES_LOCKOUT_PARAMETERS = ['ip_address']  # conta e bloqueia por IP, não por usuário
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=30)
AXES_RESET_ON_SUCCESS = True
